name: ap_common_core
description: "The school affairs(AP) series shares the engineering kit, rapid development of the school affairs series(AP) app"
version: 0.0.2
homepage: https://github.com/abc873693/ap_common
repository: https://github.com/abc873693/ap_common/tree/master/packages/ap_common_core

environment:
  sdk: ^3.0.0

dependencies:
  sprintf: ^7.0.0
  intl: ">=0.16.0 <1.0.0"
  encrypt: ^5.0.1
  dio: ">=5.4.1 <6.0.0"
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.0
  timezone: ^0.9.4
  jwt_decoder: ^2.0.1
  json_annotation: ^4.6.0
  injector: ^4.0.0

dev_dependencies:
  lint: ^2.1.2
  build_runner: ^2.0.3
  json_serializable: ^6.3.0