name: ap_common_announcement_ui
description: "The school affairs(AP) series shares the engineering kit, rapid development of the school affairs series(AP) app"
version: 0.0.3
homepage: https://github.com/abc873693/ap_common
repository: https://github.com/abc873693/ap_common/tree/master/packages/ap_common_announcement_ui


environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  ap_common_flutter_core: ^0.0.3
  ap_common_flutter_ui: ^0.0.3
  # Dart Packages
  path: ^1.9.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.0
  sprintf: ^7.0.0
  # UI Package
  photo_view: ^0.15.0
  cached_network_image: ^3.3.1
  flutter_linkify: ^6.0.0
  # Third-party Login Package
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
