name: ap_common_firebase
description: ap_common for firebase instructure
version: 0.17.0-dev.1
homepage: https://github.com/abc873693/ap_common
repository: https://github.com/abc873693/ap_common/tree/master/packages/ap_common_firebase

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter

  ap_common_flutter_core: ^0.0.2
#    path: ../../GitHub-NKUST-ITC/ap_common
  url_launcher: ^6.1.0
  #firebase must use particular version
  firebase_core: ^2.30.0
  firebase_analytics: ^10.10.7
  firebase_crashlytics: ^3.5.7
  firebase_messaging: ^14.9.4
  firebase_remote_config: ^4.4.7
  firebase_performance: ^0.9.4+7

dev_dependencies:
  flutter_test:
    sdk: flutter


#dependency_overrides:
#  ap_common:
#    path: ../../GitHub-NKUST-ITC/ap_common
