name: ap_common
description: The school affairs(AP) series shares the engineering kit, rapid development of the school affairs series(AP) app
version: 0.25.3
homepage: https://github.com/abc873693/ap_common
repository: https://github.com/abc873693/ap_common/tree/master/packages/ap_common

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  ap_common_core: ^0.0.1
  ap_common_flutter_core: ^0.0.1
  ap_common_flutter_platform: ^0.0.1

  # Dart Packages
  sprintf: ^7.0.0
  intl: ">=0.16.0 <1.0.0"
  multiple_localization: ^0.5.0
  encrypt: ^5.0.1
  dio: ">=5.4.1 <6.0.0"
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.0
  timezone: ^0.9.4
  jwt_decoder: ^2.0.1
  json_annotation: ^4.6.0
  # Flutter UI Package
  photo_view: ^0.15.0
  barcode_widget: ^2.0.1
  barcode: ^2.2.1
  pdf: ^3.8.1
  auto_size_text_pk: ^3.0.0
  flutter_linkify: ^6.0.0
  cupertino_back_gesture: ^0.1.0

#dependency_overrides:
#  ap_common_core:
#    path: ../ap_common_core/
#  ap_common_flutter_core:
#    path: ../ap_common_flutter_core/

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.3
  json_serializable: ^6.3.0
  spider: ^4.2.2

flutter:
  assets:
    - assets/images/
    - assets/icons/

false_secrets:
  - /example/lib/main.dart
  - /example/web/index.html
  - /website/node_modules/selfsigned/README.md