name: ap_common

packages:
  - apps/**
  - packages/**

command:
  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false

scripts:
  analyze:
    exec: dart analyze .
  clean:
    run: |
      melos clean