name: ap_common_example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+10001

environment:
  sdk: ^3.5.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_sign_in_dartio: 0.3.0

  ap_common:
      path: ../../packages/ap_common

  encrypt: any
  http: any
  sprintf: any
  slang: ^4.14.0
  slang_flutter: ^4.14.0

  ap_common_plugin: 1.0.1-dev.9
#    path: ../../../GitHub/ap_common_plugin

  ap_common_flutter_core: ^1.1.0-dev.10
dependency_overrides:
  intl: 0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  slang_build_runner: ^4.14.0
  build_runner: ^2.4.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/