name: ap_common_plugin
description: ap_common Native Plugin
version: 1.0.1-dev.4
homepage: https://github.com/abc873693/ap_common
repository: https://github.com/abc873693/ap_common/tree/master/packages/ap_common_plugin

environment:
  sdk: ^3.5.0
  flutter: ">=3.0.0"

resolution: workspace

dependencies:
  ap_common_core: ^1.0.1-dev.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.rainvisitor.ap_common_plugin
        pluginClass: ApCommonPlugin
      ios:
        pluginClass: ApCommonPlugin