name: ap_common_plugin
description: ap_common Native Plugin
version: 0.4.1
homepage: https://github.com/abc873693/ap_common_plugin

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: me.rainvisitor.ap_common_plugin
        pluginClass: ApCommonPlugin
      ios:
        pluginClass: ApCommonPlugin