name: ap_common_flutter_ui
description: "The school affairs(AP) series shares the engineering kit, rapid development of the school affairs series(AP) app"
version: 0.0.2
homepage: https://github.com/abc873693/ap_common
repository: https://github.com/abc873693/ap_common/tree/master/packages/ap_common_flutter_ui

environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  ap_common_flutter_core: ^0.0.2 <1.0.0'
  # Dart Package
  sprintf: ^7.0.0
  # Flutter UI Package
  photo_view: ^0.15.0
  barcode_widget: ^2.0.1
  barcode: ^2.2.1
  pdf: ^3.8.1
  auto_size_text_pk: ^3.0.0
  flutter_linkify: ^6.0.0
  cupertino_back_gesture: ^0.1.0
  # Flutter Native Plugin
  package_info_plus: ^8.0.2
  flutter_keyboard_visibility: ^6.0.0
  printing: ^5.10.4
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  spider: ^4.2.2

flutter:
  assets:
    - assets/images/
    - assets/icons/