name: ap_common_flutter_core
description: "The school affairs(AP) series shares the engineering kit, rapid development of the school affairs series(AP) app"
version: 1.1.0-dev.7
homepage: https://github.com/abc873693/ap_common
repository: https://github.com/abc873693/ap_common/tree/master/packages/ap_common_flutter_core


environment:
  sdk: ^3.5.0
  flutter: ">=3.22.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  ap_common_core: ^1.0.1-dev.4
  dio: ^5.7.0
  intl: ">=0.16.0 <1.0.0"
  cross_file: ^0.3.4+2
  slang: ^4.14.0
  slang_flutter: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  slang_build_runner: ^4.14.0
  build_runner: ^2.4.0

flutter:
