name: ap_common_flutter_core
description: "The school affairs(AP) series shares the engineering kit, rapid development of the school affairs series(AP) app"
version: 0.0.2
homepage: https://github.com/abc873693/ap_common
repository: https://github.com/abc873693/ap_common/tree/master/packages/ap_common_flutter_core


environment:
  sdk: ^3.4.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  ap_common_core: ^0.0.3
  dio: 5.6.0
  intl: ">=0.16.0 <1.0.0"
  multiple_localization: ^0.5.0
  cross_file: ^0.3.4+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

flutter_intl:
  enabled: true
  class_name: ApLocalizations
  main_locale: 'zh_TW'
  arb_dir: lib/src/l10n
  output_dir: lib/src/l10n
  use_deferred_loading: true
