name: CI Test
on:
  push:
    tags-ignore:
      - v*
  pull_request:
    branches:
      - master
    paths-ignore:
      - "docs/**"
      - "website/**"
      - "**.md"

jobs:
  build:
    name: Flutter Build Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - uses: bluefireteam/melos-action@v3
        with:
          run-bootstrap: false
          melos-version: '6.1.0'
      - name: 'Bootstrap package'
        run: melos bootstrap
      - name: Run Test
        run: melos run test --no-select
      - name: Analyze files
        run: melos run analyze-ci
      - name: Build Web
        run: flutter build web
        working-directory: ./apps/example
#      - name: Run Flutter Driver tests
#        run: flutter drive
#        working-directory: ./apps/example