name: Document Preview
on:
  pull_request:
    paths:
      - "docs/**"
      - "website/**"
jobs:
  document_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Build
        working-directory: ./website
        run: |
          yarn
          yarn run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AP_COMMON }}'
          projectId: ap-common
          entryPoint: "website"
          channelId: "document-preview"
          expires: 7d